### ISSUE TITLE
Ui5 RatingIndicator, make it bindable

### ISSUE THREAD

**Issue by maltenorstroem** [theNorstroem/furo-ui5#12]
Supported types:
- `double`, `float`, `int32`, `uint32`, `sint32`, `fixed32`, `sfixed32`, `int64`, `uint64`, `sint64`, `fixed64`, `sfixed64`
- `google.protobuf.DoubleValue`, `google.protobuf.FloatValue`, `google.protobuf.Int32Value`, etc.
- `furo.fat.Doube`, `furo.fat.Float`, `furo.fat.Int32`, etc.
- `furo.BigDecimal`

https://sap.github.io/ui5-webcomponents/playground/components/RatingIndicator/
tag: _furo-ui5-rating-indicator_

**Comment by veith** [comment]
Wow, a lot of types are supported.

**Comment by maltenorstroem** [comment]
@veith basically the same types as for a number input.
