### ISSUE TITLE
FuroUi5ReferenceSearch, leaving searcher behaviours

### ISSUE THREAD

**Issue by maltenorstroem** [theNorstroem/furo-ui5#32]
**Issue**
Misleading behaviour when leaving the searcher if no element was selected from the result list.

**Current behaviour**
The model is only updated when a result is actively selected from the list. If the user leaves the field with a search term and does not select a result, the model does not change, but the search term remains in the field, suggesting that this value has been stored in the model.

**Desired behaviour**
The user is clearly informed that no result has been selected.

**Comment by veith** [comment]
It would suffice to present the text corresponding to the model on the blur event.
