### ISSUE TITLE
Issue 

### ISSUE THREAD

**Issue by MarcOmlin** [theNorstroem/furo-ui5#56]
Es wird eine falsche tooltip warnung für einen floatingpoint input.

![2022-06-02_15-21-26](https://user-images.githubusercontent.com/42028916/171640608-efdf0520-a707-4d55-9f8b-1a4f80a80c72.png)

- Es kommt eine integer Warnung bei numerischen Feldern (tooltip)
- aber 11.4 ist eigentlich gültig
- Kann aber sein dass das Teil einfach einen step 0.01  haben will

**Comment by veith** [comment]
Der Tooltip kommt vom nativen Element selbst (Browser). Du musst einen "korrekten" **step** eintragen um das nicht zu bekommen.
