### ISSUE TITLE
furo-ui5-time-picker-labeled errors when using it

### ISSUE THREAD

**Issue by MarcOmlin** [theNorstroem/furo-ui5#62]
I am using furo-ui5-time-picker-labeled for reporting a time-slot. 

Clientcode looks like this:

```
            <furo-ui5-time-picker-labeled
              newline
              double
              format-pattern="HH:mm"
              fn-focus="--data"
              fn-bind-data="--data(*.zeit_von)"
            ></furo-ui5-time-picker-labeled>

            <furo-ui5-time-picker-labeled
              double
              format-pattern="HH:mm"
              fn-bind-data="--data(*.zeit_bis)"
            ></furo-ui5-time-picker-labeled>
```

version -> package.json:
```
"@furo/ui5": "^1.7.1",
```

Muspec-Definition looks like this:
```
    zeit_bis: '* google.type.TimeOfDay:4 = 00:00 #Zeitfeld bis'
    zeit_von: '* google.type.TimeOfDay:3 = 00:00 #Zeitfeld von'
```

Currently when i try to type 0 into the furo-ui5-time-picker-labeled (Bis)

<img width="1919" alt="Zeiteintrag_0" src="https://user-images.githubusercontent.com/42028916/177722845-c1b294df-c829-48e7-a5b3-1a8e0510d117.png">

then i get the following error-message:
```
furo-ui5-time-picker.js:131 Uncaught TypeError: Cannot read properties of null (reading 'getHours')
    at FuroUi5TimePicker._updateFNA (furo-ui5-time-picker.js:131:44)
    at FuroUi5TimePicker.<anonymous> (furo-ui5-time-picker.js:105:12)
    at FuroUi5TimePicker._fireEvent (UI5Element.js:720:34)
    at FuroUi5TimePicker.fireEvent (UI5Element.js:687:28)
    at TimePickerBase.js:266:9
    at Array.forEach (<anonymous>)
    at FuroUi5TimePicker._updateValueAndFireEvents (TimePickerBase.js:265:10)
    at FuroUi5TimePicker._handleInputLiveChange (TimePickerBase.js:284:8)
    at EventPart.handleEvent (lit-html.ts:1685:29)
    at Input._fireEvent (UI5Element.js:706:38)
_updateFNA @ furo-ui5-time-picker.js:131
(anonymous) @ furo-ui5-time-picker.js:105
_fireEvent @ UI5Element.js:720
fireEvent @ UI5Element.js:687
(anonymous) @ TimePickerBase.js:266
_updateValueAndFireEvents @ TimePickerBase.js:265
_handleInputLiveChange @ TimePickerBase.js:284
handleEvent @ lit-html.ts:1685
_fireEvent @ UI5Element.js:706
fireEvent @ UI5Element.js:687
fireEventByAction @ Input.js:1271
await in fireEventByAction (async)
_handleInput @ Input.js:1052
handleEvent @ lit-html.ts:1685
```

Waht can i change to bring this to work?
Do i need to change the type google.type.TimeOfDay to something else?

Thx for any advice

greets marc

**Comment by veith** [comment]
the defaults you used in your spec is not correct =00:00 should be removed or set with = {"hour":0,"minute":0}
https://developers.google.com/ad-manager/api/reference/v202205/ForecastService.TimeOfDay

**Comment by veith** [comment]
you deleted the field hour and minute and replaced it with a string

**Comment by MarcOmlin** [comment]
@veith Thx for this Tip
It is not working for me. 

I found a workaround to fix the initial bug.
when i send a timeofday and not null it works like expected.
But if i remove the time from the field and then it loses focus then it sets null on the internal value.
When you now try to insert a new value then you have the same issue. 

-> nullpointer because the internal value is null and you cannot use the method getHours() on it. 

when you can fix the null-value set on leaving the empty field then it should be fine i think.
