### ISSUE TITLE
Furo Multiselect (2 mehr)

### ISSUE THREAD

**Issue by MarcOmlin** [theNorstroem/furo-ui5#70]
Fehler welcher noch korrigiert werden sollte. 

LG Marc

![2022-09-28_11-42-19](https://user-images.githubusercontent.com/42028916/196941935-81ec9f4f-cc04-4b14-928c-9f361da5ce4d.png)

**Comment by veith** [comment]
Thank you Marc, this problem is solved in release 1.14.2
